name: flutter_custom_dropdown_list
description: A customizable dropdown package for Flutter that allows developers to display a dropdown.
version: 1.0.1
homepage: https://github.com/gmadhu27
repository: https://github.com/gmadhu27/flutter_custom_dropdown

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
